Custom/urls.py
from django.urls import path
from Custom import views
from Custom.forms import forgetpass
from rest_framework.urlpatterns import format_suffix_patterns
# from .views import registration_view, home, log_in,logout, changepassword, forgetpassword, reset, user_api

urlpatterns = [
    path("", views.home, name = "Home"),
    path("register/",views.registration_view, name = "register"),
    path("thanks/", views.thanks, name = "thanks"),
    path("login/", views.log_in, name="login"),
    path('logout/', views.logout, name = "logout"),
    path("changepassword/", views.changepassword, name  = "changepassword"),
    path("loggedout/", views.loggedout, name  = "loggedout"),
    path("forgetpass/", views.forgetpassword, name = "forgetpass"),
    path("reset/<int:pk>", views.reset, name = "Resset"),
    path("getuser/<int:pk>", views.user_api.as_view(), name = "userapi")   
]
# urlpatterns  = format_suffix_patterns(urlpatterns)

customadmin/urls.py
from django.urls import path
from customadmin import views
from django.contrib.auth import views as auth_views
from Custom.api import views as api_views
# from customadmin.views.Author import AuthorAjaxPagination


app_name  = "customadmin"

urlpatterns = [
    path("",views.Login.as_view() , name  = "cust_admin_login" ),
    path("index/", views.IndexView.as_view(), name = "index"),
    path("book-list/",views.BookList.as_view(), name = "book-list"),
    path('author-list/',views.AuthorListView.as_view(),name='author-list'),
    path('transaction-list/',views.TransactionListView.as_view(),name='transaction-list'),
    path('book-change/<int:pk>', views.BookUpdateView.as_view(),name='book-update'),
    path('author-change/<int:pk>',views.AuthorUpdateView.as_view(),name='author-update'),
    path('transaction-change/<int:pk>',views.TransactionUpdateView.as_view(),name='transaction-update'),
    path('book-delete/<int:pk>',views.BookDeleteView.as_view(),name='book-delete'),
    path('author-delete/<int:pk>',views.AuthorDeleteView.as_view(),name='author-delete'),
    path('transaction-delete/<int:pk>',views.TransactionDeleteView.as_view(),name='transaction-delete'),
    path('book-create/',views.BookCreateView.as_view(),name='book-create'),
    path('author-create/',views.AuthorCreateView.as_view(),name='author-create'),
    path('transaction-create/',views.TransactionCreateView.as_view(),name='transaction-create'),
    path('ajax-author', views.AuthorAjaxPagination.as_view(), name = "author-list-ajax"),
    path('ajax-book', views.BookAjaxPagination.as_view(), name = "book-list-ajax"),
    path('ajax-transaction', views.TransactionAjaxPagination.as_view(), name = "transaction-list-ajax"),
    path('logout/',views.logout.as_view(), name = "logout")
    
	# path("ajax-agency-user", AgencyUserAjaxPagination.as_view(), name="agencyuser-list-ajax"),
]
    

userAuthCustom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
     path('customadmin/', include("customadmin.urls")),
     path('api/', include('Custom.api.urls',  namespace='api')), 
     path('admin/', admin.site.urls),
     path("", include('Custom.urls')),
     path('api-auth/', include('rest_framework.urls'))
   
]

Custom/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractBaseUser   , BaseUserManager , PermissionsMixin
 
class myUserManager(BaseUserManager):
    def create_user(self, name, email, password = None, **kwargs):
        if not name:
            raise ValueError("Please Enter Name")
        if not email:
            raise ValueError("Email is required")
        user  = self.model(
            name  = name,
            email = self.normalize_email(email)
        )
        user.set_password(password)

        user.save(using = self._db)
        
        return user
    def create_superuser(self, name, email,password = None, **kwargs):
        user = self.create_user(
            name = name,
             email = self.normalize_email(email),
              password= password
            )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using  = self._db)
        return user
        
class myUser(AbstractBaseUser, PermissionsMixin):

    name = models.CharField(max_length=50, verbose_name=" User Name: ")
    email = models.EmailField(max_length=50,unique=True, verbose_name="E-mail Address :")
    is_active =  models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin=models.BooleanField(default=False)
    is_superuser = models.BooleanField(default = False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['name']
    objects  = myUserManager()
    def __str__(self):
        return self.name
    
    def has_perm(self, perm, obj = None):
        
        return self.is_admin
    def has_perms(self, perm, obj= None):
        return True

    def has_module_perms(self, app_label):
        return True
    

class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=40, unique=True)
    

    def __str__(self):
        return self.name +  " "+  self.email

class book(models.Model):
    
    title = models.CharField(max_length=50, unique=True)
    category = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="author_books")
    
    

    

    def __str__(self):
        return self.title


class transaction(models.Model):
    user = models.ForeignKey(myUser, related_name="user_has_books", on_delete= models.CASCADE)
    books = models.ForeignKey(book, related_name ="book_transactions",on_delete=models.CASCADE)
    issue_date = models.DateTimeField(default=datetime.now())
    return_date = models.DateTimeField(null=True)
       


    # *******************************************************************************************







class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name

class Writer(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    authors = models.ManyToManyField(Writer)
    number_of_comments = models.IntegerField(default=0)
    number_of_pingbacks = models.IntegerField(default=0)
    rating = models.IntegerField(default=5)

    def __str__(self):
        return self.headline

customadmin/models.py
from django.db import models
from Custom.models import *

customadmin/views/Author.py
from Custom.models import  Author
from customadmin.views.generic import MyCreateView, MyDeleteView, MyListView, MyUpdateView, MyLoginRequiredView
# from django.views import View
from django.db.models import Q
from django.template.loader import get_template
from django_datatables_too.mixins import DataTableMixin
from django.urls import reverse
from django.http import JsonResponse
from customadmin.forms import AuthorCreateForm, AuthorUpdateForm


from customadmin.mixins import HasPermissionsMixin

class AuthorListView(MyListView):
    ordering = ["-id"]
    model = Author
    queryset = model.objects.all()
    template_name = "customadmin/author/author_list.html"
    permission_required = ("Custom.view_Author",)
class AuthorCreateView(MyCreateView):
    model = Author
    form_class = AuthorCreateForm
    template_name = "customadmin/author/author_update.html"
    permission_required = ("Custom.add_author",)

    def form_valid(self, form):
        form.instance.create_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        # opts = self.model._meta
        return reverse("customadmin:author-list")
class AuthorUpdateView(MyUpdateView):
    model = Author
    form_class = AuthorUpdateForm
   
    template_name = "customadmin/author/author_update.html"
    permission_required = ("Custom.change_author",)

    def get_success_url(self):
      
        return reverse("customadmin:author-list")
class AuthorDeleteView(MyDeleteView):
    model = Author
    template_name = "customadmin/confirm_delete.html"
    permission_required = ("Custom.delete_Author",)

    def get_success_url(self):
       
        return reverse("customadmin:author-list")



class AuthorAjaxPagination(DataTableMixin, HasPermissionsMixin, MyLoginRequiredView):
    """
    Ajax-Pagination view for ReviewCategory
    """
    model = Author
    queryset = model.objects.all().order_by("-id")

    def _get_is_superuser(self, obj):
        """Get boolean column markup."""
        t = get_template("customadmin/partials/list_boolean.html")
        return t.render({"bool_val": obj.is_superuser})

    def is_orderable(self):
        """Check if order is defined in dictionary."""
        # if self._querydict.get("order"):
        #     return True
        return True

    def _get_actions(self, obj):
        """Get actions column markup."""
        t = get_template("customadmin/partials/list_row_actions.html")
        opts = self.model._meta
        return t.render({
            "o": obj,
            "opts": opts,
            "has_change_permission": self.has_change_permission(self.request),
            "has_delete_permission": self.has_delete_permission(self.request),
        })

    def filter_queryset(self, qs):
        """Return the list of items for this view."""
        # If a search term, filter the query
        if self.search:
            return qs.filter(
                Q(name__icontains=self.search) |
                Q(email__icontains=self.search)
            )
        return qs

    def prepare_results(self, qs):
        """Prepare final result data here."""
        # Create row data for datatables
        data = []
        for o in qs:
        #     if o.slug:
        #         slug = o.slug
        #     else:
        #         slug = '-'
            # url = reverse("customadmin:author-list", kwargs={'pk': o.pk})
            data.append(
                {
                    "id": o.id,
                    # "name":  "<a href='" + url + "'>" + o.name + "</a>",
                    "name": o.name,
                    "email":o.email,
                    
                    "actions": self._get_actions(o),
                }
            )
        return data

    def get(self, request, *args, **kwargs):
        context_data = self.get_context_data(request)
        total_filter_data = len(self.filter_queryset(self.model.objects.all().order_by("-id")))
        context_data['recordsTotal'] = len(self.model.objects.all().order_by("-id"))
        context_data['recordsFiltered'] = total_filter_data
        return JsonResponse(context_data)

customadmin/views/book.py
from Custom.models import book
from customadmin.views.generic import MyCreateView, MyDeleteView, MyListView, MyUpdateView, MyLoginRequiredView
from django.urls import reverse
from customadmin.forms import BookCreateForm, BookUpdateForm

from customadmin.mixins import HasPermissionsMixin
from django.db.models import Q
from django.template.loader import get_template
from django_datatables_too.mixins import DataTableMixin
from django.urls import reverse
from django.http import JsonResponse


class BookList(MyListView):
    ordering = ["-id"]
    model = book
    queryset = model.objects.all()
    template_name = "customadmin/book/book_list.html"
    permission_required = ("Custom.view_book",)


class BookCreateView(MyCreateView):
    model = book
    form_class = BookCreateForm
    template_name = "customadmin/review_category/review_category_form.html"
    permission_required = ("Custom.add_book",)

    def form_valid(self, form):
        form.instance.create_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        # opts = self.model._meta
        return reverse("customadmin:book-list")
class BookUpdateView(MyUpdateView):
    model = book
    form_class = BookUpdateForm
   
    template_name = "customadmin/review_category/review_category_form.html"
    permission_required = ("Custom.change_book",)

    def get_success_url(self):
      
        return reverse("customadmin:book-list")

class BookDeleteView(MyDeleteView):
    model = book
    template_name = "customadmin/confirm_delete.html"
    permission_required = ("Custom.delete_book",)

    def get_success_url(self):
        print("------------inside delsucurl_-----------------------")
        return reverse("customadmin:book-list")


class BookAjaxPagination(DataTableMixin, HasPermissionsMixin, MyLoginRequiredView):
    """
    Ajax-Pagination view for ReviewCategory
    """
    model = book
    queryset = model.objects.all().order_by("-id")

    def _get_is_superuser(self, obj):
        """Get boolean column markup."""
        t = get_template("customadmin/partials/list_boolean.html")
        return t.render({"bool_val": obj.is_superuser})

    def is_orderable(self):
        """Check if order is defined in dictionary."""
        # if self._querydict.get("order"):
        #     return True
        return True

    def _get_actions(self, obj):
        """Get actions column markup."""
        t = get_template("customadmin/book/book_actions.html")
        opts = self.model._meta
        return t.render({
            "o": obj,
            "opts": opts,
            "has_change_permission": self.has_change_permission(self.request),
            "has_delete_permission": self.has_delete_permission(self.request),
        })

    def filter_queryset(self, qs):
        """Return the list of items for this view."""
        # If a search term, filter the query
        if self.search:
            return qs.filter(
                Q(title__icontains=self.search) |
                Q(category__icontains=self.search)
            )
        return qs

    def prepare_results(self, qs):
        """Prepare final result data here."""
        # Create row data for datatables
        data = []
        for o in qs:
        #     if o.slug:
        #         slug = o.slug
        #     else:
        #         slug = '-'
            # url = reverse("customadmin:author-list", kwargs={'pk': o.pk})
            data.append(
                {
                    "id": o.id,
                    # "name":  "<a href='" + url + "'>" + o.name + "</a>",
                    "title": o.title,
                    "author":o.author.name,
                    "category":o.category,
                    "actions": self._get_actions(o),
                }
            )
        return data

    def get(self, request, *args, **kwargs):
        context_data = self.get_context_data(request)
        total_filter_data = len(self.filter_queryset(self.model.objects.all().order_by("-id")))
        context_data['recordsTotal'] = len(self.model.objects.all().order_by("-id"))
        context_data['recordsFiltered'] = total_filter_data
        return JsonResponse(context_data)

customadmin/views/index.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from Custom.models import book, Author, transaction
from django.shortcuts import render


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "customadmin/index.html"
    context = {}

    def get(self, request):
        self.context['review_categories'] = book.objects.all().count()
        self.context['review_brands'] = Author.objects.all().count()
        self.context['reviews'] = transaction.objects.all().count()
        return render(request, self.template_name, self.context)

customadmin/views/login.py
# import imp
from graphviz import view
from Custom.forms import LogPage
from Custom.models import myUser
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.views import View
from Custom.models import book, Author, transaction, myUser


class Login(View):
    
    def get(self,request):
        context = {}
        form = LogPage()
        context['form']  = form
        return render(request,"Custom/login.html", context)
    def post(self,request):


        context= {}
        context['review_categories'] = book.objects.all().count()
        context['review_brands'] = Author.objects.all().count()
        context['reviews'] = transaction.objects.all().count()
        if request.method  == 'POST':
               
            form = LogPage(request.POST)
            context['form'] = form
       
            if form.is_valid():
       
                email =  form.cleaned_data.get('email')
                password = form.cleaned_data.get('password')
                user = myUser.objects.filter(email = email).first()
           
                if user:

       
                   account = authenticate(email = email, password = password)
                    
                   if account:
                       if account.has_perm("is_admin", account):
                        login(request, user)
                        redirect('/index')
                        return render(request,"customadmin/index.html", context)
                       else:
                        return HttpResponse("YOU are not a superuser")
                   else:
                        return HttpResponse("password or email is wrong")
                else:
                    return  HttpResponse("NO user exists")
           
            else:
           
                return render(request, "customadmin/ebr/registration/login.html",{'form':form} )


class logout(View):

    def get(self, request):
        logout(request)
        render(request,'Custom.loggedout.html')

customadmin/templates/customadmin/change_form.html
{% extends 'customadmin/base_section.html' %}
{% load static %}
{% load widget_tweaks %}
{% load admin_extras %}
{% load misc_filters %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block title %}
    {% if object.pk %}Change{% else %}Add{% endif %} {{ opts.verbose_name|capfirst }} - {{ opts.verbose_name_plural|capfirst }}
{% endblock%}


{% block page_header %}

{% if opts.verbose_name_plural == 'groups' %}

{% if object.pk %}Change{% else %}Add{% endif %} New Role

{% else %}

{% if object.pk %}Change{% else %}Add{% endif %} {{ opts.verbose_name|capfirst }}

{% endif %}


{% endblock%}





{% block current_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:index' %}">{% trans 'Home' %}</a>
</li>
{% if opts.verbose_name_plural != 'Users' %}
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:book-list' %}">{% trans opts.verbose_name_plural %}</a>
</li>
{% else %}
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:index' %}">{% trans opts.verbose_name_plural %}</a>
</li>
{% endif %}
<li class="breadcrumb-item active">

    {% if opts.verbose_name_plural == 'groups' %}

    {% if add %}{% blocktrans with name=opts.verbose_name %}Add Role {% endblocktrans %}{% else %}{{ object|truncatewords:"18" }}{% endif %}

    {% else %}

    {% if add %}{% blocktrans with name=opts.verbose_name %}Add {{ name }}{% endblocktrans %}{% else %}{{ object|truncatewords:"18" }}{% endif %}

    {% endif %}
</li>



{% endblock %}


{% block formset_errors %}
    {% include "customadmin/partials/form_errors.html" with form=form %}
{% endblock%}


{% block page_content %}
    Change form content goes here.
{% endblock %}

customadmin/templates/customadmin/change_list.html
{% extends 'customadmin/base_section.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}


{% block title %}
    {{ opts.verbose_name_plural|capfirst }}
{% endblock%}


{% block page_header %}
    {% if opts.verbose_name_plural == 'groups' %}
      User Roles
    {% else %}
      {{ opts.verbose_name_plural|capfirst }}
    {% endif %}
{% endblock%}


{% block current_breadcrumb %}
  <li class="breadcrumb-item">
      {% comment %} <a href="{% url 'customadmin:index' %}">{% trans 'Home' %}</a> {% endcomment %}
  </li>
  <li class="breadcrumb-item active">
    {% if opts.verbose_name_plural == 'groups' %}
      User Roles
    {% else %}
      {{ opts.verbose_name_plural|capfirst }}
    {% endif %}
  </li>
{% endblock%}


{% block page_content %}
    Changelist content goes here.
{% endblock %}

customadmin/templates/customadmin/confirm_delete.html
{% extends 'customadmin/base_section.html' %}
{% load misc_filters %}
{% load i18n %}

{% block title %}
    Delete {{ opts.verbose_name|capfirst }} - {{ opts.verbose_name_plural|capfirst }} {{ block.super }}
{% endblock%}


{% block page_header %}
    Delete {{ opts.verbose_name|capfirst }}
{% endblock%}


{% block current_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:index' %}">{% trans 'Home' %}</a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:book-list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:book-update' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
</li>
<li class="breadcrumb-item active">
    {% trans 'Delete' %}
</li>
{% endblock %}


{% block page_content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <h3>{{ title }}</h3>

            {% if perms_lacking %}
                <p>{% blocktrans with object_name=opts.verbose_name escaped_object=object %}Deleting the {{ object_name }} "{{ escaped_object }}" would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:{% endblocktrans %}</p>
                <ul>
                {% for obj in perms_lacking %}
                    <li>{{ obj }}</li>
                {% endfor %}
                </ul>

            {% elif protected %}
                <p>{% blocktrans with object_name=opts.verbose_name escaped_object=object %}Deleting the {{ object_name }} "{{ escaped_object }}" would require deleting the following protected related objects:{% endblocktrans %}</p>
                <ul>
                {% for obj in protected %}
                  <li>{{ obj }}</li>
                {% endfor %}
                </ul>

            {% else %}
                <p>{% blocktrans with object_name=opts.verbose_name escaped_object=object %}Are you sure you want to delete the {{ object_name }} "{{ escaped_object }}"? All of the following related items will be deleted:{% endblocktrans %}</p>
                {% comment %} <p class="alert alert-danger">{% block delete_message %}{% endblock %} This action cannot be undone.</p> {% endcomment %}
                {% include "customadmin/includes/object_delete_summary.html" %}
                <h4>{% trans "Objects" %}</h4>
                <ul>{{ deleted_objects|unordered_list }}</ul>
            {% endif %}

        </div>
    </div>

    <div class="modal-footer">
        <a href="{% url 'customadmin:book-list' %}" class="btn btn-white"><i class="fa fa-times"></i> Cancel</a>

        {% if not perms_lacking and not protected and has_delete_permission %}
        {% comment %} <input type="submit" value="Yes, I'm Sure" class="btn btn-danger"/> {% endcomment %}
        <button class="btn btn-danger" onclick="myPageLoader()" type="submit"><i class="fa fa-check"></i> Yes, I'm Sure</button>
        {% endif %}
    </div>
</form>
{% endblock page_content %}

customadmin/templates/customadmin/home_change_form.html
{% extends 'customadmin/home_section.html' %}
{% load static %}
{% load widget_tweaks %}
{% load admin_extras %}
{% load misc_filters %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block title %}
    {% if object.pk %}Change{% else %}Add{% endif %} {{ opts.verbose_name|capfirst }} - {{ opts.verbose_name_plural|capfirst }}
{% endblock%}


{% block page_header %}
    {% if object.pk %}Change{% else %}Add{% endif %} {{ opts.verbose_name|capfirst }}
{% endblock%}


{% block current_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:index' %}">{% trans 'Home' %}</a>
</li>
<li class="breadcrumb-item">
    {% if has_view_permission %}<a href="{% url opts|admin_urlname:'list' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
</li>
<li class="breadcrumb-item active">
    {% if add %}{% blocktrans with name=opts.verbose_name %}Add {{ name }}{% endblocktrans %}{% else %}{{ object|truncatewords:"18" }}{% endif %}
</li>
{% endblock %}


{% block formset_errors %}
    {% include "customadmin/partials/form_errors.html" with form=form %}
{% endblock%}


{% block page_content %}
    Change form content goes here.
{% endblock %}

customadmin/templates/customadmin/sidebar.html
{% load static %}
{% load admin_extras %}

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">

            <li class="nav-header">
                
                    {% comment %} <img class="nav-image" src="{% static 'customadmin/img/logo.svg' %}" width="100%" /> {% endcomment %}
                {% comment %} </a> {% endcomment %}
                <div class="logo-element">
                    UC
                </div>
            </li>
          

<!--            {% if perms.customadmin.add_user or perms.customadmin.view_user or perms.customadmin.change_user or perms.customadmin.delete_user or request.user.is_superuser %}-->
<!--                <li {% if 'users/' in request.path %}class="active" {% endif %}>-->
<!--                    <a href="">-->
<!--                        <i class="fa fa-user fa-fw fa-2x"></i>-->
<!--                        <span class="nav-label">Users</span>-->
<!--                    </a>-->
<!--                </li>-->
<!--            {% endif %}-->

            {% if perms.Custom.add_book or perms.Custom.view_book or perms.Custom.change_book or perms.Custom.delete_book or request.user.is_superuser %}
                <li {% if 'book/' in request.path %} class="active" {% endif %}>
                    <a href="{% url 'customadmin:book-list'%}">
                        <i class="fa fa-list-alt fa-fw fa-2x"></i>
                        <span class="nav-label">Book</span>
                    </a>
                </li>
            {% endif %}


            {% if perms.Custom.add_Author or perms.Custom.view_Author or perms.Custom.change_Author or perms.Custom.delete_Author or request.user.is_superuser %}
            <li {% if 'author/' in request.path %} class="active" {% endif %}>
                <a href="{% url 'customadmin:author-list'%}">
                    <i class="fa fa-list-alt fa-fw fa-2x"></i>
                    <span class="nav-label">Author</span>
                </a>
            </li>
        {% endif %}


        {% if perms.Custom.add_transaction or perms.Custom.view_transaction or perms.Custom.change_transaction or perms.Custom.delete_transaction or request.user.is_superuser %}
                <li {% if 'transaction/' in request.path %} class="active" {% endif %}>
                    <a href="{% url 'customadmin:transaction-list'%}">
                        <i class="fa fa-list-alt fa-fw fa-2x"></i>
                        <span class="nav-label">Transactions</span>
                    </a>
                </li>
            {% endif %}




          
          

        </ul>
    </div>
</nav>